### ISSUE TITLE
missing installation instructions

### ISSUE THREAD

**Issue by jippi** [burdandrei/vault-aws-letsencrypt#1]
how do I install this? looks great!

**Comment by burdandrei** [comment]
how about now?

**Comment by jippi** [comment]
Thanks, I installed it in my production environment and now all my data is gone - how do I roll back?

**Comment by burdandrei** [comment]
just `terraform destroy`, it will destroy back the void of all your data!

**Comment by jippi** [comment]
Thank you, that worked, however it seems like restoring my data from the void had some odd (undocumented) side effects.

How do I get rid of the Dimensional Horror from my infrastructure? 

![image](https://github.com/burdandrei/vault-aws-letsencrypt/assets/22841/fc362e60-460f-421e-9ee8-c2f6bd6fef47)

![image](https://github.com/burdandrei/vault-aws-letsencrypt/assets/22841/3db2eccb-dc35-4c8f-b46d-85bc31a54444)

**Comment by johnyzed** [comment]
> just `terraform destroy`, it will destroy back the void of all your data!

dont forget -auto-approve

**Comment by burdandrei** [comment]
unfortunately it's a known issue, but our PS team will be happy to assist you with this

![image](https://github.com/burdandrei/vault-aws-letsencrypt/assets/2526486/aa46cfb2-6013-4950-bb29-41a984f7fcdf)
